momo5502/sogen

- src/windows-emulator/devices/afd_endpoint.cpp
- src/windows-emulator/devices/afd_types.hpp
- src/windows-emulator/io_device.hpp
- src/windows-emulator/process_context.hpp
- src/windows-emulator/windows_emulator.cpp
> Add poll support

- src/windows-emulator/syscalls.cpp
For now, this is reports as not implemented but it seems to make the OS happy.
> added missing syscall so that Windows 10 emulation works

- src/windows-emulator-test/emulation_test_utils.hpp
- src/windows-emulator-test/time_test.cpp
- src/windows-emulator/syscall_dispatcher.cpp
- src/windows-emulator/windows_emulator.cpp
- src/windows-emulator/windows_emulator.hpp
The idea here is to start exposing various high level callbacks from various sub components (syscalls, device io, etc.).
Consumer of `windows_emulator` can then hook into any callback.
Please give your feedback on this initial commit.
> Exposing high level callbacks

- src/emulator/memory_manager.hpp
allow inspecting regions from the emulator object. this is useful for writing advanced tools that use the windows_emulator library
> exposed region inspection methods

- CMakeLists.txt
- src/emulator/memory_manager.cpp
- src/emulator/memory_manager.hpp
The idea is to allow as much internal information into inner components. to not burden all builds, the reflection level can be controlled via the MOMO_REFLECTION_LEVEL (where 0 means no reflection code is included).
more reflection variables will be introduced as needed.
For now, the memory manager's layout state version is used to track whether the memory layout is changed or not (at the lowest level). the win_emu API consumer can use this reflection to decide to whether to refresh or not expensive computations
> Introducing reflection levels concept into core components

- .github/workflows/build.yml
This will always use the windows release test sample artifacts. It doesn't really make sense to test the debug artifacts. They're just slower and do the same.
This will still run debug artifacts on windows.
The change only applies to non-windows platforms
> Always use release windows artifacts

- src/common/utils/time.hpp
- src/windows-emulator/windows_emulator.cpp
Previously, RDTSC in the VM always returned a constant value of 4, which broke any timing-based operations, or caused detections in heuristics of malware and ANTI-VM tools.
This patch introduces a spoofed rdtsc_fake counter that tracks and adjusts timing deltas to simulate realistic TSC increments. Can be extended to simulate rdtsc timings based on CPU clock speed.
> feat: spoof rdtsc timings

- src/common/platform/file_management.hpp
- src/common/platform/process.hpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/exception.cpp
- src/windows-emulator/syscalls/file.cpp
- src/windows-emulator/syscalls/memory.cpp
- src/windows-emulator/syscalls/section.cpp
- src/windows-emulator/syscalls/thread.cpp
- src/windows-emulator/syscalls/token.cpp
This PR fixes various things that allow a basic .NET app compiled as native to run.
1. Fixes the length types of NtQueryVirtualMemory.
2. Ignore unimplemented APC flags and log a warning instead.
3. Implements NtQueryFullAttributesFile.
4. Implements TokenOwner @ NtQueryInformationToken.
5. Adds support for reserving memory @ NtMapViewOfSection.
6. Adds support for unmapping reserved memory @ NtUnmapViewOfSection.
The code of the .NET app that was used to test:
The settings of the .NET app:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>Exe</OutputType>
<TargetFramework>net8.0</TargetFramework>
<ImplicitUsings>enable</ImplicitUsings>
<Nullable>enable</Nullable>
<PublishAot>true</PublishAot>
</PropertyGroup>
</Project>
```
> fix(syscalls): fix VirtualQuery return size, ignore unimplemented APC flags and log a warning.

- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/file.cpp
- src/windows-emulator/syscalls/section.cpp
- src/windows-emulator/syscalls/thread.cpp
This PR aims to fix an issue with NtOpenSection where it would fail with "Unsupported section" if the RootDirectory was "BASE_NAMED_OBJECTS_DIRECTORY", it also adds handlers for "NtOpenThread" (stub), "NtUserGetProcessWindowStation" (stub) and "NtFlushBuffersFile".
As you can see from the changes, the `NtOpenThread` handler simply returns `STATUS_NOT_SUPPORTED`. I don't know if there's anything better I could do, but this was enough to get around it in the executable I was trying to run.
> Fix NtOpenSection and add 3 new syscall handlers

- src/windows-emulator/process_context.cpp
- src/windows-emulator/process_context.hpp
- src/windows-emulator/syscalls.cpp
While trying to run some executables I noticed handlers for `NtUserRegisterClassExWOW`/`NtUserUnregisterClass` were necessary, so this PR aims to add them. Also, while working on this PR I noticed that atoms should be ref-counted, so this PR also does that.
I found a previous abandoned PR that aimed to add it (https://github.com/momo5502/emulator/pull/101), so I took some of the feedback from that and added a common function in process_context to handle the atoms, I hope that's ok.
> Add more atom-related syscalls

- src/common/platform/registry.hpp
- src/common/utils/container.hpp
- src/windows-emulator/registry/hive_parser.cpp
- src/windows-emulator/registry/hive_parser.hpp
- src/windows-emulator/registry/registry_manager.cpp
- src/windows-emulator/registry/registry_manager.hpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/registry.cpp
This PR aims to improve registry handling by keeping the key names casing in the map intact so they can be queried and the caller gets them in their proper casing. It also implements the `NtEnumerateKey` and `NtEnumerateValueKey` syscalls.
> registry: Implement case-preserving key names and enumeration syscalls

- src/common/platform/kernel_mapped.hpp
- src/windows-emulator/process_context.cpp
- src/windows-emulator/process_context.hpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/locale.cpp
- src/windows-emulator/syscalls/port.cpp
- src/windows-emulator/syscalls/section.cpp
- src/windows-emulator/syscalls/system.cpp
- src/windows-emulator/syscalls/thread.cpp
This PR aims to do the following:
- Add the `NtUserGetAtomName` syscall.
- Add stub handlers for `NtUserSetWindowsHookEx`, `NtUserUnhookWindowsHookEx`, and `NtUserCreateWindowEx`.
- Implement `NtGetNlsSectionPtr` (for Code Pages), add `NtQueryDefaultUILanguage`, and improve `NtQueryInstallUILanguage`.
- Handle `SystemTimeZoneInformation`, `SystemCurrentTimeZoneInformation`, and `SystemDynamicTimeZoneInformation` in `NtQuerySystemInformation`.
- Skip `ThreadAffinityMask` in `NtSetInformationThread`.
- Fix `NtConnectPort` to allow TimeZone queries to work properly. This is probably the most problematic change here because it required messing with the shared section and hardcoding an offset (2504). Initializing the data in this offset seems necessary for calls like `GetTimeZoneInformation` …
> Improvements to locale syscalls, fix TimeZone query and add more syscalls

- src/tools/create-root.bat
- src/windows-emulator/registry/registry_manager.cpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/port.cpp
- src/windows-emulator/syscalls/process.cpp
- src/windows-emulator/syscalls/registry.cpp
- src/windows-emulator/syscalls/section.cpp
- [Update `create-root.bat`](https://github.com/momo5502/sogen/commit/21fc460db83192464ce0f8773a92ecedb5acbe4f) with more dlls and NLS-related files.
- [Retry loading using normal path when wow6432node path is not found](https://github.com/momo5502/sogen/commit/16e7cac48af4e88c3ee3710a6e3a335e1486adb5), I'm not sure if this is the right thing to do, but I guess Windows does something like this behind the scenes because the saved `wow6432node` doesn't contain all the keys that exist when you look at it in regedit.
- [Add stub for NtAreMappedFilesTheSame and modify NtSetInformationKey to return success](https://github.com/momo5502/sogen/commit/8dfcf2755c3fca1da36a2334ad40c4e55728a048).
- [Simplify the TimeZone query …
> Various fixes, update to create-root.bat and a new syscall

- src/common/platform/process.hpp
- src/samples/test-sample/test.cpp
- src/tools/create-root.bat
- src/windows-emulator/registry/registry_manager.cpp
- src/windows-emulator/syscalls/system.cpp
- src/windows-emulator/syscalls/token.cpp
- [Add new tests](https://github.com/momo5502/sogen/commit/9d0de32cde149a492c771dd7db8d523f0c82a4ab), specifically tests for the new registry features were added, as well as a check for the GetSystemDirectory (this breaks if the SharedSection is incorrectly configured). This already helped me [fix a bug](https://github.com/momo5502/sogen/commit/0474eef3737455e00dd890c41c88dc55bca80569) in the `WOW6432Node` redirection under Linux!
- [Handle TokenGroups in NtQueryInformationToken](https://github.com/momo5502/sogen/commit/7fef4ebc24f6fc831fe86f785d7130ea7346c3d2), [Stub SystemFirmwareTableInformation in NtQuerySystemInformation](https://github.com/momo5502/sogen/commit/3b918f2d5cd867d05b7dd1bc9633ed4b88efe84b). These two changes allow executables protected with Themida to …
> Add new tests and some syscall fixes

- src/common/utils/container.hpp
- src/common/utils/string.hpp
- src/common/utils/wildcard.hpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/file.cpp
- src/windows-emulator/windows_objects.hpp
- src/windows-emulator/windows_path.hpp
- [Stub FileBasicInformation in NtSetInformationFile](https://github.com/momo5502/sogen/commit/6d0ad1dd61454bacdc41ad869d5b82c17540dc9d)
- [Make sure a root `windows_path` have slash at the end](https://github.com/momo5502/sogen/commit/02ed4fbb033135844ec0986fb4ca6fac73b45a3e), this was necessary because `directory_iterator` fails when the path is `C:` (without slash)..
- [Improve NtQueryDirectoryFileEx](https://github.com/momo5502/sogen/commit/f6ec1fc9cca448fc8de031cba1a5dd492e530087) by adding filename filtering support, including more basic file information in the struct, and fixing an issue that prevented the last chunk of files from being enumerated correctly.
> Improvements to NtQueryDirectoryFileEx

- src/common/platform/kernel_mapped.hpp
- src/common/utils/container.hpp
- src/samples/test-sample/test.cpp
- src/windows-emulator/process_context.cpp
- src/windows-emulator/process_context.hpp
- src/windows-emulator/registry/registry_manager.hpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/file.cpp
- src/windows-emulator/syscalls/process.cpp
- src/windows-emulator/syscalls/section.cpp
- src/windows-emulator/windows_emulator.cpp
- [Fix TimeZoneInformation](https://github.com/momo5502/sogen/commit/496fbd3a407e66a191e8cfa73fea77def2c6bdc6) by moving `wDayOfWeek` to the end of the `SYSTEMTIME` structure. This goes against the public definitions of the `SYSTEMTIME` struct but I can confirm that this yields correct values when `GetTimeZoneInformation` is called.
- [Load environment variables from registry](https://github.com/momo5502/sogen/commit/9d5338b1680a7b0e25b2547895c6cac934e02eeb).
- [Miscellaneous fixes](https://github.com/momo5502/sogen/commit/a629f77e31ef4a40ebe8e8b845d398478ecc6bdd), to be more specific:
- Add `NtOpenProcess` syscall stub.
- Add logging to `handle_file_enumeration`.
- Fix `FILE_ATTRIBUTE_NORMAL` being together with `FILE_ATTRIBUTE_DIRECTORY` (`FILE_ATTRIBUTE_NORMAL` means …
> Load environment variables from registry and other fixes

- src/windows-emulator/io_device.cpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/file.cpp
- src/windows-emulator/syscalls/registry.cpp
- [Add a new device to create_device](https://github.com/momo5502/sogen/commit/75ee63803cc286a5ea8192a74f3c769e8c310591).
- [Improve handling of NtCreateKey](https://github.com/momo5502/sogen/commit/4888142d224356e43b9d3537ca70c48800df74b3), to be more specific, it now opens keys that already exist.
- [Fix some issues in some file syscalls](https://github.com/momo5502/sogen/commit/3e1f206bc00f75d82cc271f03ac2c9b7397137f1).
> Fixes to some file syscalls and improve handling of `NtCreateKey`

- src/windows-emulator/devices/afd_endpoint.cpp
- src/windows-emulator/devices/afd_endpoint.hpp
- src/windows-emulator/io_device.cpp
- src/windows-emulator/syscalls.cpp
- src/windows-emulator/syscalls/file.cpp
This PR aims to fix both blocking and non-blocking socket connect operations inside the emulator.  
The previous implementation of `ioctl_connect` was a bit wrong, and the `afd_async_connect_hlp` device is necessary for non-blocking sockets.
> Fix afd_endpoint::ioctl_connect

- src/windows-emulator/syscalls/memory.cpp
Fixes #421 
Ensures sogen handles two edge cases correctly:
- VirtualAlloc with size 0 and invalid flags now returns STATUS_INVALID_PARAMETER instead of terminating emulation with an exception.
- VirtualFree with an invalid free_type now fails cleanly, as per Windows behavior.
Using test code from #421  before change:
Executing syscall: NtAllocateVirtualMemory (0x18) at 0x180162bb2 via 0x103858074 (KernelBase.dll)
Syscall threw an exception: 18 (0x180162bb2) - Unsupported allocation type!
Emulation terminated without status!
After:
Executing function: kernel32.dll - VirtualAlloc (0x103703c90) via (0x14000119a) Valloc.exe
Executing syscall: NtAllocateVirtualMemory (0x18) at 0x180162bb2 via 0x103858074 (KernelBase.dll)
Executing function: kernel32.dll - GetLastError (0x1036e8640) via …
> fix: handle two invalid VirtualAlloc/Free edge cases correctly

- src/windows-emulator/windows_emulator.cpp
Fixes a bug where `perform_context_switch_work` method erases the thread from the threads list and call its destructor but doesn't invalidate the `active_thread` property causing the following switch_to_thread call to call `active_thread->save(emu);` when `active_thread` is already destroyed and thus throws an exception when assigning to `last_registers`.
> Fix exception when NtTerminateThread is called on the active thread.
